server.port=8081
user.service.message=Service is running from config server(github)
management.tracing.sampling.probability=1.0
managment.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

spring.datasource.username=root
spring.datasource.password={cipher}6e0be90803d92efebb08c7462ba5945cfc439af037838a41808e1735340a7431
